### ISSUE TITLE
bugs 

### ISSUE THREAD

**Issue by ProDash1998** [PaulTDD-MC/BanManager#2]
[23:46:54] [Server thread/INFO]: ProDash issued server command: **/tempban ProDash**
[23:46:54] [Server thread/ERROR]: Unhandled exception executing command 'tempban' in plugin BanManager v1.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'tempban' in plugin BanManager v1.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1322]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:416) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1322]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1322]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1322]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.cryptical.banmanager.commands.COMMAND_Tempban.onCommand(COMMAND_Tempban.java:56) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1322]
	... 18 more
[23:46:59] [Server thread/INFO]: ProDash issued server command: /tempban ProDash 10m reload
[23:46:59] [Server thread/INFO]: ProDash lost connection: [Ban Manager]

You have been banned from this server

Reason: reload 
Expires: 23:56 8-2-2018
Banned by: ProDash

Want to get unbanned? Contact us here http://yourlink.com/

**Comment by ProDash1998** [comment]
[23:51:25] [Server thread/INFO]: [BanManager] Updated player data (file)
[23:52:40] [User Authenticator #1/INFO]: UUID of player ProDash is 4a77aabb-e4fa-4629-9c8d-2ee92a877ce2
[23:52:40] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to BanManager v1.0.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[spigot.jar:git-Paper-1322]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-Paper-1322]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Paper-1322]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [spigot.jar:git-Paper-1322]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:175) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:65) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1322]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at org.cryptical.banmanager.utils.Database.get(Database.java:118) ~[?:?]
	at org.cryptical.banmanager.utils.Database.contains(Database.java:176) ~[?:?]
	at org.cryptical.banmanager.events.onPlayerJoinEvent.onPlayerJoin(onPlayerJoinEvent.java:17) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-Paper-1322]
	... 15 more

**Comment by PaulTDD-MC** [comment]
What arguments did you use in the command tempban?

**Comment by ProDash1998** [comment]
the error is in every command

**Comment by PaulTDD-MC** [comment]
Can you show me your config.yml?

**Comment by ProDash1998** [comment]
https://pastebin.com/v4Kk2yL7 - default

**Comment by PaulTDD-MC** [comment]
What files are in your languages folder?

**Comment by ProDash1998** [comment]
lang_en

**Comment by PaulTDD-MC** [comment]
mhm

**Comment by PaulTDD-MC** [comment]
For /tempban; What argument did you include after

**Comment by ProDash1998** [comment]
tempban <nick> 10m reason
Add information for the same tempban / tempmute "tempban / tempmute <nick> <time> <reason>"
I found another error, I do not write what a mute got. sory for my eng

**Comment by PaulTDD-MC** [comment]
Pleas post screens of /bm about and /bm userinfo < yourname >

**Comment by ProDash1998** [comment]
the commands run once and not once https://www.youtube.com/edit?o=U&video_id=9-fOB51AJbQ

https://imgur.com/a/pQGKA
[12:54:01 INFO]: ProDash issued server command: /bm userinfo
[12:54:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bm' in plugin BanManager v1.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1322]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1322]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1322]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at org.cryptical.banmanager.commands.MainCommand.onCommand(MainCommand.java:135) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1322]
        ... 15 more

**Comment by PaulTDD-MC** [comment]
Owh, do u use paper spigot??

**Comment by PaulTDD-MC** [comment]
The youtube link you send doens't work

**Comment by ProDash1998** [comment]
https://youtu.be/9-fOB51AJbQ

**Comment by PaulTDD-MC** [comment]
What minecraft version do you use?

**Comment by ProDash1998** [comment]
only 1.12.2

**Comment by PaulTDD-MC** [comment]
hmm, It's very odd. Are you using a database as backend or flatfile?

**Comment by ProDash1998** [comment]
Mysql Maria DB (currently I do not use your plugins)

**Comment by PaulTDD-MC** [comment]
Which is quite understandable, since it is not working on your server...
I will look into it. Can you please give me any errors which you haven't given to me?

**Comment by ProDash1998** [comment]
only so far I have found

**Comment by PaulTDD-MC** [comment]
Okay then, thanks anyway.
